import { Html } from '@react-three/drei';
import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import gsap from 'gsap';
import portfolio from '../../../data/portfolio';

function Boot({ refName, distanceFactor, htmlPosition, htmlRotation }) { return <Html transform wrapperClass="bootScreen" distanceFactor={distanceFactor} position={htmlPosition} rotation={htmlRotation} rotation-x={-0.256} ref={refName}><img src="./images/boot_sequence.gif" alt="Helen Creative Desk is initializing" /></Html>; }
function Back({ navigate, prominent = false, label = '返回工作台' }) { return <button className={`desk-back${prominent ? ' desk-back--floating' : ''}`} type="button" onClick={() => navigate('desk')}>← {label}</button>; }
function Welcome({ navigate }) { const enterDesk = () => navigate('desk'); return <section className="workstation welcome-cover welcome-cover--interactive" onClick={enterDesk}><div className="welcome-copy"><div><p className="ws-system">HELEN CREATIVE DESK / 01</p><p className="ws-name">{portfolio.identity.nameZh} / {portfolio.identity.nameEn.toUpperCase()}</p></div><div className="welcome-main"><p className="ws-tagline">产品 · AI · 设计 · Coding</p><h1><span>把想法做成，</span><span>真正可以被使用的产品。</span></h1><p className="ws-note">这里放着一些，<br />我认真做出来的东西。</p><button className="enter-desk" type="button" onClick={(event) => { event.stopPropagation(); enterDesk(); }}>进入工作台 <span aria-hidden="true">→</span></button><p className="ws-english">AI PRODUCT CREATOR<br />I TURN IDEAS INTO PRODUCTS.</p></div></div><aside className="welcome-graphic" aria-label="Digital Sun future lab graphic"><div className="welcome-graphic__grid" /><div className="welcome-graphic__sun" /><div className="welcome-graphic__horizon welcome-graphic__horizon--one" /><div className="welcome-graphic__horizon welcome-graphic__horizon--two" /><div className="welcome-graphic__horizon welcome-graphic__horizon--three" /><span className="welcome-graphic__index">01 / 04</span><span className="welcome-graphic__year">2026</span><span className="welcome-graphic__ready">SYSTEM READY</span><span className="welcome-graphic__caption">AI / PRODUCT / DESIGN / CODE</span><i className="welcome-graphic__accent" /></aside></section>; }
function Desk({ navigate }) { return <section className="workstation desk-home"><header><p className="ws-system">01 / 04 · INDEX</p><div className="desk-home__identity"><p>HELEN CREATIVE DESK</p><button type="button" onClick={() => navigate('welcome')}>← 返回首页</button></div></header><div className="desk-directory">{portfolio.navigation.map((item) => <button type="button" key={item.label} onClick={() => navigate(item.page)}><span>{item.number}</span><div><b>{item.label}</b><strong>{item.title}</strong><small>{item.detail}</small></div><i aria-hidden="true">↗</i></button>)}</div></section>; }
function LinkOrStatus({ project }) { const url = project.caseStudyUrl || project.projectUrl; return url ? <a className="project-link" href={url} target="_blank" rel="noopener noreferrer">{project.featured ? '查看完整案例' : '查看项目'} ↗</a> : <span className="project-status">{project.status}</span>; }
function ProjectCard({ project }) { const url = project.caseStudyUrl || project.projectUrl; const openProject = (event) => { if (!url || event.target.closest('a')) return; window.open(url, '_blank', 'noopener,noreferrer'); }; const handleKeyDown = (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openProject(event); } }; return <article className={`${project.featured ? 'project-featured' : 'project-secondary'}${url ? ' project-card--linked' : ''}`} role={url ? 'link' : undefined} tabIndex={url ? 0 : undefined} aria-label={url ? `打开 ${project.name} 项目网站` : undefined} onClick={openProject} onKeyDown={handleKeyDown}><p className="ws-system">{project.label}</p><div className="project-preview" aria-label={`${project.name} 项目视觉预览占位`}>PROJECT PREVIEW</div><h2>{project.name}</h2><h3>{project.englishName}</h3><p className="project-type">{project.type}</p><p className="project-description">{project.description}</p><div className="project-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><LinkOrStatus project={project} /></article>; }
function Projects({ navigate }) { return <section className="workstation scroll-view"><Back navigate={navigate} prominent /><header className="page-heading"><p className="ws-system">PROJECT INDEX</p><h1>项目作品</h1><span>Selected Work</span></header><div className="project-stack">{portfolio.projects.map((project) => <ProjectCard key={project.name} project={project} />)}</div></section>; }

function FilmPoster({ film, compact = false }) { return <div className={`film-poster${compact ? ' film-poster--compact' : ''}`}><img src={film.posterSrc} alt={`${film.title} 作品封面`} loading="lazy" /><span>作品封面</span><i aria-hidden="true">{film.number}</i></div>; }
function FilmCard({ film, openFilm }) { return <button className="ai-film-card" type="button" onClick={() => openFilm(film.id)} aria-label={`查看 ${film.title} 详情`}><FilmPoster film={film} /><span className="ai-film-card__hover">查看作品 ↗</span><div className="ai-film-card__meta"><span>{film.number}</span><b>{film.englishTitle}</b><strong>{film.title}</strong><small>{film.tag}</small></div></button>; }
function AiLab({ navigate, openFilm }) { const selected = portfolio.aiLab.films.filter((film) => film.selected); const more = portfolio.aiLab.films.filter((film) => !film.selected); return <section className="workstation scroll-view ai-film-archive"><Back navigate={navigate} prominent /><header className="ai-film-archive__heading"><p className="ws-system">{portfolio.aiLab.kicker}</p><h1>{portfolio.aiLab.titleZh}</h1><span>{portfolio.aiLab.subtitle}</span><p>{portfolio.aiLab.introduction.split('\n').map((line, index) => <span key={`${line}-${index}`}>{line || <br />}</span>)}</p><small>{portfolio.aiLab.tags}</small></header><section className="ai-film-section"><header><p>SELECTED WORKS</p><span>精选作品</span></header><div className="ai-film-grid ai-film-grid--selected">{selected.map((film) => <FilmCard key={film.id} film={film} openFilm={openFilm} />)}</div></section><section className="ai-film-section ai-film-section--more"><header><p>MORE WORKS</p><span>更多作品</span></header><div className="ai-film-grid ai-film-grid--more">{more.map((film) => <FilmCard key={film.id} film={film} openFilm={openFilm} />)}</div></section></section>; }
function FilmDetail({ film, backToLab, backToHome, openFilm }) { const currentIndex = portfolio.aiLab.films.findIndex((item) => item.id === film.id); const nextFilm = portfolio.aiLab.films[(currentIndex + 1) % portfolio.aiLab.films.length]; return <section className="workstation scroll-view ai-film-detail"><nav className="ai-film-detail__nav" aria-label="作品页导航"><button className="desk-back" type="button" onClick={backToLab}>← 返回影像作品</button><button className="desk-back" type="button" onClick={backToHome}>返回首页</button></nav><header><p className="ws-system">项目 {film.number} / {film.tag}</p><h1>{film.englishTitle}</h1><strong>{film.title}</strong><span>{film.tag}</span><p>{film.description}</p></header><section className="ai-film-detail__media"><p>作品视频</p><video key={film.id} className="ai-film-video" controls preload="metadata" playsInline poster={film.posterSrc} aria-label={`播放 ${film.title}`}><source src={film.videoSrc} type="video/mp4" />你的浏览器暂不支持播放此视频。</video></section><section className="ai-film-detail__facts"><div><span>作品类型</span><b>{film.type}</b></div><div><span>创作重点</span><b>{film.focus}</b></div></section><button className="ai-film-detail__next" type="button" onClick={() => openFilm(nextFilm.id)}>下一个项目 <span>{nextFilm.title}</span> →</button></section>; }

function About({ navigate }) {
  const [resumeOpen, setResumeOpen] = useState(false);
  const pageRef = useRef(null);
  const modalRef = useRef(null);
  const closeResume = () => {
    const modal = modalRef.current;
    if (!modal) return setResumeOpen(false);
    const paper = modal.querySelector('.resume-lightbox__paper');
    gsap.to(paper, { opacity: 0, y: 26, scale: .98, duration: .22, ease: 'power2.in' });
    gsap.to(modal, { opacity: 0, duration: .22, ease: 'power2.in', onComplete: () => setResumeOpen(false) });
  };
  useEffect(() => {
    const items = pageRef.current?.querySelectorAll('[data-about-reveal]');
    if (!items?.length) return undefined;
    const context = gsap.context(() => { gsap.fromTo(items, { autoAlpha: 0, y: 17 }, { autoAlpha: 1, y: 0, duration: .58, ease: 'power2.out', stagger: .09, clearProps: 'transform' }); }, pageRef);
    return () => context.revert();
  }, []);
  useEffect(() => {
    if (!resumeOpen) return undefined;
    const onKeyDown = (event) => { if (event.key === 'Escape') closeResume(); };
    window.addEventListener('keydown', onKeyDown);
    const context = gsap.context(() => {
      gsap.fromTo(modalRef.current, { autoAlpha: 0 }, { autoAlpha: 1, duration: .22, ease: 'power1.out' });
      gsap.fromTo(modalRef.current.querySelector('.resume-lightbox__paper'), { autoAlpha: 0, y: 42, scale: .97 }, { autoAlpha: 1, y: 0, scale: 1, duration: .5, ease: 'power3.out', delay: .03 });
    }, modalRef);
    return () => { window.removeEventListener('keydown', onKeyDown); context.revert(); };
  }, [resumeOpen]);
  const resumeModal = resumeOpen && createPortal(<div className="resume-lightbox resume-lightbox--fullscreen" ref={modalRef} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) closeResume(); }}><section className="resume-lightbox__paper" role="dialog" aria-modal="true" aria-labelledby="resume-lightbox-title"><header><div><p className="ws-system">RESUME / 邱玉婷</p><h2 id="resume-lightbox-title">个人简历</h2></div><button type="button" onClick={closeResume} aria-label="关闭简历预览">关闭 ×</button></header><div className="resume-lightbox__body"><img src="/resume/qiu-yuting-resume-preview.webp" alt="邱玉婷完整个人简历" /></div><footer><a href="/resume/qiu-yuting-resume.pdf" target="_blank" rel="noopener noreferrer">查看原始 PDF ↗</a><a href="/resume/qiu-yuting-resume.pdf" download="qiu-yuting-resume.pdf">下载简历 ↓</a></footer></section></div>, document.body);
  return <section className="workstation scroll-view about-page" ref={pageRef}><Back navigate={navigate} /><div className={`about-layout${resumeOpen ? ' about-layout--dimmed' : ''}`}><article className="about-profile"><header data-about-reveal><p className="ws-system">ABOUT / 03</p><h1>关于我</h1></header><div className="about-profile__intro" data-about-reveal><p>我从数字出版和 AIGC 设计出发，<br />现在把产品思考、视觉表达和 AI Coding<br />放在同一个工作流里。</p><p>比起只停留在想法里，<br />我更喜欢把一个问题做成<br />能够被验证、被使用、被继续迭代的产品。</p></div><dl className="about-profile__facts" data-about-reveal><div><dt>BACKGROUND</dt><dd>深圳职业技术大学<br />数字出版</dd></div><div><dt>EXPERIENCE</dt><dd>AIGC 设计相关工作经验</dd></div><div><dt>DIRECTION</dt><dd>产品 / AI 产品</dd></div><div><dt>PROJECTS</dt><dd>《真要买吗》<br />《我的島嶼車票》</dd></div></dl></article><aside className="resume-preview" data-about-reveal><p className="ws-system">OPEN RESUME FILE</p><button className="resume-card" type="button" onClick={() => setResumeOpen(true)} aria-haspopup="dialog" aria-label="打开邱玉婷的全屏简历预览"><div className="resume-card__top"><span>RESUME / 2026</span><i aria-hidden="true">↗</i></div><img src="/resume/qiu-yuting-resume-preview.webp" alt="邱玉婷个人简历预览" /><div className="resume-card__footer"><span>放大查看简历</span><b>↗</b></div></button></aside></div>{resumeModal}</section>;
}
function Workstation({ refName, distanceFactor, htmlPosition, htmlRotation }) { const [page, setPage] = useState('welcome'); const [activeFilmId, setActiveFilmId] = useState(null); const navigate = (next) => setPage(next); const activeFilm = portfolio.aiLab.films.find((film) => film.id === activeFilmId); const openFilm = (id) => { setActiveFilmId(id); setPage('filmDetail'); }; return <Html transform wrapperClass="productOsScreen" distanceFactor={distanceFactor} position={htmlPosition} rotation={htmlRotation} rotation-x={-0.256} ref={refName} style={{ opacity: 0, display: 'none' }}><main className="workstation-shell">{page === 'welcome' && <Welcome navigate={navigate} />}{page === 'desk' && <Desk navigate={navigate} />}{page === 'projects' && <Projects navigate={navigate} />}{page === 'aiLab' && <AiLab navigate={navigate} openFilm={openFilm} />}{page === 'filmDetail' && activeFilm && <FilmDetail film={activeFilm} backToLab={() => setPage('aiLab')} backToHome={() => setPage('welcome')} openFilm={openFilm} />}{page === 'about' && <About navigate={navigate} />}</main></Html>; }
export default function Screens({ isOpen, isPoweredOn, isFinishedBooting, bootScreenRef, linkedInScreenRef, htmlPosition, htmlRotation, distanceFactor }) { return <>{isOpen && isPoweredOn && !isFinishedBooting && <Boot refName={bootScreenRef} distanceFactor={distanceFactor} htmlPosition={htmlPosition} htmlRotation={htmlRotation} />}<Workstation refName={linkedInScreenRef} distanceFactor={distanceFactor} htmlPosition={htmlPosition} htmlRotation={htmlRotation} /></>; }
